CREATE TABLE pessoa (
	id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	data_nascimento DATE NOT NULL,
	rg VARCHAR(50) NOT NULL,
	cpf VARCHAR(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;